language: ruby
rvm:
- 2.3.1
services:
- redis
before_script:
- RACK_ENV=test bundle exec rake db:create && bundle exec rake db:migrate
env:
  global:
    secure: ljSHnQyQE72jQyPUfrrTwqTrEBtJBayOQOj+fwvU0566r4GlCpJvebYmY2qmNDkymfeV3c0jsN2WaqUmgD2ehYP9cImW7moyvrefGCXHs0D8KuHJwSlC+Ux5xA9HyRTJk+k2yQpcUIlQa7RYti21gwrmYbhJ1TfLoVKrhya66DJH0pPM8LqrJ/CBHVjU9o79uCylrMUrmtRFnU3lDIEGacH/LnbJO4wsLhjpoFP8CnvHYSQpxBPtMxoUYtdltUrrXW5f3lzTQhCXEBVdo/UACfQvLi+mYQ8Vu2ockbAQHYO2ghvUZsO1X4At7kc1omZEGqzRz1FsY4N64orsWyaJFSHBXSLhVoUj3INNnACoYA+x4w5J/nFkWfElcB0D2xVJQGzdoF1JcHGSW8ICakrJIrdTs8uieraix3z2lM2QOu2yXUdEFLpF7MJJc3/1Gb8oOcZhY8HMbSqsm/h6G1Dnzt/iCUyIPNXO5U61kDXW+/bzCJjL/XwSdBgtxq15nzMf81mZKktRZRk48yPCHU6wEc1ZIXv16R+kdbhDAxVYmSIGSroErkQtoHHK1Cao+HQpT3/241n94KbSdxGah2+1CbAfKxitvaZHpH6Gfp73fhulejRmZCpZxdE77a045Q6hHpc7gdE+tiLuojRTfp6ntnpQCWqM+qDXaKw00xSmDIo=
